# Use root/example as user/password credentials
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: app_backend
    links:
      - db
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: dbmongo
    ports:
      - ${DB_PORT}:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}