version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rpg-manager
    ports:
      - "5234:5234"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5234"]
      timeout: 10s
      retries: 5
volumes:
  db:
    driver: local
